### ISSUE TITLE
SVG images 

### ISSUE THREAD

**Issue by vamsikrishnav** [Artawower/awesome-mac#1]
Hi Artawower,

I am really impressed by awesome-mac. I want to know where(which website) you got your SVG images which are used in your firefox homepage? I want to get more such images.

Regards
Vamsi

**Comment by Artawower** [comment]
If i remember correctly, i used [this website](https://www.flaticon.com/free-icons/social-media?word=social%20media&shape=hand-drawn&order_by=4)

**Comment by vamsikrishnav** [comment]
thank you so much!
